### PR TITLE
Remove 32 byte limit for plain I2C

### PR DESCRIPTION
**Pull request by sgoll**
When using `raspi-i2c` to send or receive plain I2C data, the payload need not be limited to 32 bytes. This pull request lifts that limitation.

See #9 and fivdi/i2c-bus#23 for more information.

### CODE REVIEW

**Comment by nebrius** [comment]
This looks good at a quick glance to me, but I'd like to get @fivdi's input first since he wrote it.

**Comment by fivdi** [comment]
It also looks good to me. `lib/index.js` needs to be generated with babel.

**Comment by nebrius** [comment]
Bump, can you regenerate the built file @sgoll? Then this should be ready to land.

**Comment by sgoll** [comment]
@nebrius Done.

**Comment by nebrius** [comment]
Perfect, thanks @sgoll, and thanks again for taking the time to submit a PR!

**Comment by nebrius** [comment]
Just so you know, I'll try and get the update published to npm soon, but it may take me a few days to get to it. This is technically a breaking change and thus a semver major bump, so the process is a bit more complex in terms of coordinating updating raspi-io, which has another major breaking change lined up for release too.

**Pull request merged**
